### ISSUE TITLE
Add link to Vulnurability disclosure policy

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/Fairdrop#111]
Add link to Vulnurability disclosure policy (https://github.com/fairDataSociety/vulnerability-disclosure-policy) as a menu item under the About section as well as in the message shown at the top of the page.

**Comment by crtahlin** [comment]
There should be two links in the message shown at the top of the page: one to report issues, other to link do Vulnerability disclosure policy. Suggest the text bellow the line is used.

--------------------------------------------------------------------------------------------
Fairdrop is in Beta and provided for evaluation only! File integrity, persistence and security are not assured! [Click here to report Bugs](https://github.com/fairDataSociety/Fairdrop/issues). For security vulnerabilities see [Fair Data Society Vulnerability Disclosure Policy](https://github.com/fairDataSociety/vulnerability-disclosure-policy).

**Comment by significance** [comment]
@plur9 @crtahlin thoughts on this>

**Comment by plur9** [comment]
hmm... if it fits, I'm ok with it. If not, we should maybe update the disclosure policy with the link to also report bugs, and then we have only one link in the header

**Comment by crtahlin** [comment]
I would keep them separated for ease of use - there will be many bugs, and (hopefully) a lot less security vulnerability reports. No need to expose those reporting bugs to the whole Vulnerability dis. policy.

**Comment by crtahlin** [comment]
I see that currently we have About -> Bug disclosure
I think we should have 
About -> Report bug
About -> Disclose vulnerabilty

Maybe the Report bug thing should even be somewhere on the main page. Because no one will go through the trouble of finding a link to report bugs under some menu and reading some disclosure policy. Unless its some fanatic follower with too much time on her hands.

**Comment by crtahlin** [comment]
The people that will encounter and report bugs are from a wide group of normal to power users.
The people that will find and report vulnerabilities are from a small group of white-hats (or even other shades of hat). I think they should be in separate flows, to smooth the process for bug-reporting group.

**Comment by plur9** [comment]
On the homepage, there should be one link. That link can address both. FWIW, it can go to a FAQ entry where separate links are present. However, let's keep the noise on the homepage to minimum.

**Comment by crtahlin** [comment]
Ok. @significance do you have what you need?
