### ISSUE TITLE
Terms of usage and About Fairdrop has a sideways slider

### ISSUE THREAD

**Issue by MatejKebe** [fairDataSociety/Fairdrop#127]
Terms of usage has a sideways slider, but there is nothing to slide to the right or left of the text.

![image](https://user-images.githubusercontent.com/47885079/54592793-62052980-4a2d-11e9-83ca-6ae8c8b22c14.png)

**Comment by MatejKebe** [comment]
Version:  0.3.3 - staging

**Comment by significance** [comment]
@MatejKebe what OS/browser are you using?

**Comment by MatejKebe** [comment]
Windows 10 - Chrome 73.0.3683.75
