### ISSUE TITLE
When logged in and sending unencrypted, it asks for a mailbox

### ISSUE THREAD

**Issue by MatejKebe** [fairDataSociety/Fairdrop#128]
Whn you are logged in and trying to send unencrypted it asks for a mailbox to send to. The same issue appears when you log out and try to send unencryted.

Version:  0.3.3 - staging

**Comment by MatejKebe** [comment]
Update: Tried recreating this bug and I couldn't. If you start from mailbox, not from the starting page and click unencrypted in the menu it throws you on the front page instead of asking you for a file to upload.

**Comment by significance** [comment]
cool - i have had a couple of weird things happening like that too - i will review how the state management is reset
