### ISSUE TITLE
Font looks uneven

### ISSUE THREAD

**Issue by MatejKebe** [fairDataSociety/Fairdrop#132]
If you look at "5" and "P" you can seen they look bold.
![image](https://user-images.githubusercontent.com/47885079/54812150-b822d880-4c8a-11e9-9425-4379ce88f607.png)

**Comment by MatejKebe** [comment]
Version: O.3.3 - Chrome 72

**Comment by significance** [comment]
@MatejKebe what hardware/OS are you using?

here's what it looks like on mine for reference...

<img width="628" alt="Screen Shot 2019-03-25 at 09 32 43" src="https://user-images.githubusercontent.com/130104/54909006-1812bc80-4ee1-11e9-9f01-7491de97a411.png">

**Comment by MatejKebe** [comment]
I have screen scale at 125% in Windows 10, if I change it to 100% it looks ok. So this is a problem, that is only going to be seen on smaller display sizes.

**Comment by significance** [comment]
cool - thanks.
