### ISSUE TITLE
css issue

### ISSUE THREAD

**Issue by significance** [fairDataSociety/Fairdrop#136]
![Screen Shot 2019-03-25 at 21 38 48](https://user-images.githubusercontent.com/130104/54955860-6ad28f80-4f46-11e9-93fd-8319d9b6df3f.png)

**Comment by plur9** [comment]
There's another bug here, see pic
<img width="1677" alt="Screenshot 2019-06-10 at 20 52 32" src="https://user-images.githubusercontent.com/1336797/59219204-3031d800-8bc2-11e9-8c0d-2ea8950a079e.png">
