### ISSUE TITLE
shows a white screen when I try to go back to inbox from the opened file

### ISSUE THREAD

**Issue by GasperX93** [fairDataSociety/Fairdrop#151]
Mobile, version 0.3.16.

When I try to go back to inbox from the file that I opened it shows me a white screen. So it doesn't take me back to the inbox.

![photo_2019-08-30 14 19 23](https://user-images.githubusercontent.com/47980720/64020238-6469c480-cb31-11e9-8a75-7eed57a9003c.jpeg)

**Comment by GasperX93** [comment]
I need to remove /mailbox/received from URL to get back on home screen.

**Comment by GasperX93** [comment]
@significance I can't assign this issue on you, I don't know why. Anyway, here it is :).

**Comment by crtahlin** [comment]
@GasperX93 i "upgraded" your permissions so please check if you can now assign issues.

@significance assigning issue to you.

**Comment by GasperX93** [comment]
@crtahlin It works now, tnx.
