### ISSUE TITLE
make the logo a homepage link

### ISSUE THREAD

**Issue by mmohorko** [fairDataSociety/Fairdrop#154]
When I send a file and it says "file is sent" or "file is stored" on the black screen - I keep clicking the logo thinking I will come to my inbox. A lot of people are probably going to do the same as this is the common practice.

**Comment by crtahlin** [comment]
@mmohorko you propose that clicking on logo should lead to home screen?

**Comment by plur9** [comment]
+1

When this issue is addressed it would be good to also do this then: #161
