### ISSUE TITLE
Sending unencrypted does not work

### ISSUE THREAD

**Issue by mmohorko** [fairDataSociety/Fairdrop#155]
If I just drag a file to the unencrypted area the upload never starts ... See the screenshot. 
<img width="1240" alt="Screenshot 2019-08-30 at 15 38 42" src="https://user-images.githubusercontent.com/45455085/64025168-5ff6d900-cb3c-11e9-9936-94ec4bcfed79.png">

**Comment by significance** [comment]
closed at duplicate - thanks for testing!
