### ISSUE TITLE
mailbox does not work

### ISSUE THREAD

**Issue by mmohorko** [fairDataSociety/Fairdrop#175]
Staging Faairdrop 0.4.0. -> if I try to send a file, select it from the computer and then cancel and repeat the process it first says "mailbox found", but when I try to send it changes that it can't find the mailbox ...

If I then repeat the whole thing then it suddenly works.

I don't know how to explain this properly - so I made a screen recording. Will send the video to @significance via Telegram.

**Comment by significance** [comment]
@mmohorko thanks for the recording, this is the same issue as https://github.com/fairDataSociety/Fairdrop/issues/173
