### ISSUE TITLE
I think that file download link for quick sharing should be renamed.

### ISSUE THREAD

**Issue by GasperX93** [fairDataSociety/Fairdrop#177]
I would change https://swarm.fairdatasociety.org/bzz:/c3... to https://swarm.fairdrop.io/bzz:/c3...

Simply to build awareness about Fairdrop.

**Comment by plur9** [comment]
maybe just fairdrop.xyz/bzz:/... ?

**Comment by tfius** [comment]
that would be awesome, would require some kind of forwarding to swarm.fairdatasociety.org

**Comment by plur9** [comment]
hmm, maybe not necessarily. As fairdrop already acts as gateway, so could be just nginx tweaks.

**Comment by GasperX93** [comment]
done.
