### ISSUE TITLE
vPRO - Blank screen after click  on the log-out button

### ISSUE THREAD

**Issue by GasperX93** [fairDataSociety/Fairdrop#196]
Fairdrop PRO Version 0.5.0 (staging).
Browser: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit).

Does not always happen, the blank screen appears randomly.

https://swarm2.fairdatasociety.org/bzz:/ef0390400f0f8a0a3e938e0714b94c40ebe2500147f2d0bf8b98fd2c3c31646f/Screenshot_2019-12-09_at_09.55.18.png

**Comment by GasperX93** [comment]
It works OK in Safari.

**Comment by significance** [comment]
@GasperX93 strange i'm getting no blank screens, would be great to capture this bug either by leaving dev tools open and viewing error logs or with the sentry remote tracking

**Comment by significance** [comment]
@GasperX93 are you able to replicate this dude?

**Comment by GasperX93** [comment]
Hey @significance, I am trying but I can't repeat it. Once it happens again (maybe in the next testing iteration) I will open dev tools and send you error logs.

**Comment by crtahlin** [comment]
But you had the time recorded and logging feature turned on? @significance should have the logs then, AFAIK.

**Comment by significance** [comment]
@crtahlin logs only contain errors and there's nothing as far as i can see relating to this. closing for now, we can reopen if we see the issue arise again.

**Comment by crtahlin** [comment]
@plur9 did it reoccur?

**Comment by plur9** [comment]
Sorry, opened by mistake. Didn't realise that the I accidently opened tasks from orgmode. There are probably more open :/
