### ISSUE TITLE
vPRO - Publish file -> The file chooser doesn't appear.

### ISSUE THREAD

**Issue by GasperX93** [fairDataSociety/Fairdrop#198]
Fairdrop PRO Version 0.5.0 (staging).
Browser: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)
Browser:  Safari Version 13.0.3 (14608.3.10.10.1)

**Comment by plur9** [comment]
Do you think we could automate these tests with, for example, Selenium? https://selenium.dev/

**Comment by significance** [comment]
yeah i think would be worthwhile at least to cover major user stories with e2e tests
