### ISSUE TITLE
vPRO - Upload Quick unencrypted -> can't choose a single file in file chooser.

### ISSUE THREAD

**Issue by GasperX93** [fairDataSociety/Fairdrop#202]
Fairdrop PRO Version 0.5.0 (staging).
Browser: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

If I do it drag&drop it works.

https://swarm.fairdrop.pro/bzz:/291a6d7850fe9ad929ad63953d573e9d73ca1fd6169dbae7ce63d59b1c6d5ef3/Screenshot_2019-12-09_at_11.04.46.png

**Comment by crtahlin** [comment]
@significance if fixed, please write so and refer to commit that fixes it , as per code review guide.
