### ISSUE TITLE
vPRO - Store file doesn't work if I use the account that was created on the previous version of Fairdop.

### ISSUE THREAD

**Issue by GasperX93** [fairDataSociety/Fairdrop#203]
Fairdrop PRO Version 0.5.0 (staging).
Browser: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)
Browser: Sarari Version 13.0.3 (14608.3.10.10.1)

There is a screen recording on the link below.
On the left screen, you can see the account "Gasper" that was created in the previous version of Fairdrop -> the store feature doesn't work.
On the right screen, you can see the account "Gasper8" which was created in version PRO 0.5.0 and the store feature works.

https://swarm.fairdrop.pro/bzz:/c4cd246a2121f21fd0f37a7734a5caaee8409f4b3661a13ba2536cec9d647f85/store_file_bug.mov

**Comment by GasperX93** [comment]
During the file upload process, an unnecessary screen is shown, for like a sec. 

https://swarm.fairdrop.pro/bzz:/97b6a8d2bedba87708e361c72105387cf25a5a6c4b547c99768842b67fb754c3/Screenshot_2019-12-09_at_14.36.36.png

**Comment by significance** [comment]
@plur9 am i right in thinking we are not expecting persistence from fairdrop.xyz to fairdrop PRO? or should we consider data migration?

**Comment by plur9** [comment]
We shouldn't separate free and paying customers as we're not doing a favor to ourselves. So, any user that comes to fairdrop.xyz should be able to upgrade to pro.

**Comment by significance** [comment]
cool - i’d like to have a look into Swarm syncing / backup / restore so i’ll investigate and report back

**Comment by plur9** [comment]
the only "problem" i see is local storage in browser for auth.
