### ISSUE TITLE
vPRO - Drag&Drop doesn't work (Safari)

### ISSUE THREAD

**Issue by GasperX93** [fairDataSociety/Fairdrop#204]
staging PRO Version 0.5.0
Safari Version 13.0.3 (14608.3.10.10.1)

The "drop" area doesn't appear.

https://swarm2.fairdatasociety.org/bzz:/88c23a51c16031a75ff658334b8545d5beace5a96814f0f3fedafadd03ee0a94/drag&drop.mov

**Comment by significance** [comment]
@GasperX93 this one was tricky! 🥴
