### ISSUE TITLE
vPRO - Buttons in the header are not responsive (Safari)

### ISSUE THREAD

**Issue by GasperX93** [fairDataSociety/Fairdrop#205]
Staging PRO Version 0.5.0
Safari Version 13.0.3 (14608.3.10.10.1)
 
Buttons Fairdrop, account name, log-out doesn't respond on click.

In the beginning, when I logged-in it worked fine, but after some time the buttons stopped responding.

https://swarm.fairdrop.pro/bzz:/f98854f1258129e6c3cd9d965d5d603f28c3929c41d8285cd5aa60592fd5261d/buttons_not_respond.mov

**Comment by plur9** [comment]
This could also be a selenium test.
