### ISSUE TITLE
Fairdrop doesn't work -  (XMLHttpRequest has been blocked?)

### ISSUE THREAD

**Issue by GasperX93** [fairDataSociety/Fairdrop#253]
Fairdrop version: 0.5.3, production

Please see the print screen below for details:

![image](https://user-images.githubusercontent.com/47980720/74223892-f9afde00-4cb7-11ea-9ae3-876ce0cd8e88.png)

**Comment by significance** [comment]
had a out of memory (i think RAM) error with Swarm, have restarted it

**Comment by crtahlin** [comment]
@significance does this out of memory thing warrant its own issue? has it happened before? do we know it will not happen again? do we know why it happened?

**Comment by GasperX93** [comment]
Hey, 

I just tested it again and it doesn't work jet.

**Comment by plur9** [comment]
this is on staging?
