### ISSUE TITLE
font licencing

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/Fairdrop#37]

**Comment by significance** [comment]
> Let’s remove this and go with open source version, its licensing is not ok
> […](#)
> Sent from my mobile device
> On 26 Feb 2019, at 15:08, significance ***@***.***> wrote: https://www.bertholdtypes.com/font/akzidenz-grotesk/proplus/ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

done ;D
