### ISSUE TITLE
select button doesn't open dialogue

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/Fairdrop#73]
select button doesn't open dialogue, how is this supposed to work with two options (send and encrypt)?

**Comment by significance** [comment]
@crtahlin which select button?

**Comment by crtahlin** [comment]
This one :+1: 
![image](https://user-images.githubusercontent.com/1554520/64726159-52473900-d4d6-11e9-8341-ab00709394c7.png)

Although, it seems to work now (file picker opens). So I am closing the issue.

(There is still the question of the flow after selecting a file - how to go to either encrypted | unencrypted sending. But that is not a bug.)
